# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vision_pb2 as vision__pb2


class VisionModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInference = channel.stream_stream(
                '/vision.VisionModel/StreamInference',
                request_serializer=vision__pb2.ImageFrame.SerializeToString,
                response_deserializer=vision__pb2.Prediction.FromString,
                )
        self.UpdateWeights = channel.unary_unary(
                '/vision.VisionModel/UpdateWeights',
                request_serializer=vision__pb2.WeightUpdate.SerializeToString,
                response_deserializer=vision__pb2.UpdateResponse.FromString,
                )


class VisionModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamInference(self, request_iterator, context):
        """Send image frame for inference, receive prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWeights(self, request, context):
        """Update model weights on receiver
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInference': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=vision__pb2.ImageFrame.FromString,
                    response_serializer=vision__pb2.Prediction.SerializeToString,
            ),
            'UpdateWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWeights,
                    request_deserializer=vision__pb2.WeightUpdate.FromString,
                    response_serializer=vision__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision.VisionModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VisionModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/vision.VisionModel/StreamInference',
            vision__pb2.ImageFrame.SerializeToString,
            vision__pb2.Prediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vision.VisionModel/UpdateWeights',
            vision__pb2.WeightUpdate.SerializeToString,
            vision__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
