# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\"^\n\nImageFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x17\n\x0fpointcloud_data\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"u\n\nPrediction\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\nstair_type\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\ndistance_m\x18\x04 \x01(\x02\x12\x19\n\x11inference_time_ms\x18\x05 \x01(\x03\"I\n\x0cWeightUpdate\x12\x15\n\rmodel_weights\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"1\n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x01\n\x0bVisionModel\x12=\n\x0fStreamInference\x12\x12.vision.ImageFrame\x1a\x12.vision.Prediction(\x01\x30\x01\x12=\n\rUpdateWeights\x12\x14.vision.WeightUpdate\x1a\x16.vision.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEFRAME']._serialized_start=24
  _globals['_IMAGEFRAME']._serialized_end=118
  _globals['_PREDICTION']._serialized_start=120
  _globals['_PREDICTION']._serialized_end=237
  _globals['_WEIGHTUPDATE']._serialized_start=239
  _globals['_WEIGHTUPDATE']._serialized_end=312
  _globals['_UPDATERESPONSE']._serialized_start=314
  _globals['_UPDATERESPONSE']._serialized_end=363
  _globals['_VISIONMODEL']._serialized_start=366
  _globals['_VISIONMODEL']._serialized_end=505
# @@protoc_insertion_point(module_scope)
