# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\"E\n\nImageFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x99\x01\n\nPrediction\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05label\x18\x03 \x01(\t\x12\x19\n\x11inference_time_ms\x18\x04 \x01(\x03\x12\x1e\n\x16server_receive_time_ms\x18\x05 \x01(\x03\x12\x1b\n\x13server_send_time_ms\x18\x06 \x01(\x03\"I\n\x0cWeightUpdate\x12\x15\n\rmodel_weights\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"1\n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x01\n\x0bVisionModel\x12=\n\x0fStreamInference\x12\x12.vision.ImageFrame\x1a\x12.vision.Prediction(\x01\x30\x01\x12=\n\rUpdateWeights\x12\x14.vision.WeightUpdate\x1a\x16.vision.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEFRAME']._serialized_start=24
  _globals['_IMAGEFRAME']._serialized_end=93
  _globals['_PREDICTION']._serialized_start=96
  _globals['_PREDICTION']._serialized_end=249
  _globals['_WEIGHTUPDATE']._serialized_start=251
  _globals['_WEIGHTUPDATE']._serialized_end=324
  _globals['_UPDATERESPONSE']._serialized_start=326
  _globals['_UPDATERESPONSE']._serialized_end=375
  _globals['_VISIONMODEL']._serialized_start=378
  _globals['_VISIONMODEL']._serialized_end=517
# @@protoc_insertion_point(module_scope)
